# ----------------------------------------------------------------------------------------------------------
# This is a Docker Compose file for setting up a depends_on service.

# ----------------------------------------------------------------------------------------------------------
# WARNING:
# This file is for local development and staging environments only.
# DO NOT USE THIS FILE IN PRODUCTION ENVIRONMENTS.
# ----------------------------------------------------------------------------------------------------------

services:

   service-mysql:
    container_name: "service-mysql"
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3307:3306"
    networks:
      - reverse-proxy
    volumes:
      - ./container-data/data:/var/lib/mysql
      - ./container-data/logs:/var/log/mysql
      - ./schema:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/mysql.mods-enabled/mysqld.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    cap_add:
      - SYS_NICE # CAP_SYS_NICE

networks:
  reverse-proxy:
    external: true
